name: Node.js Package

on:
  push:
    paths:
      - 'nodejs/**'
  pull_request:
    paths:
      - 'nodejs/**'
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./nodejs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Test package
        run: npm test
        env:
          FR24_PROXY_URL: ${{ secrets.FR24_PROXY_URL }}
